#!/bin/bash

set -e

IM_CONFIG_FILE="/etc/default/im-config"

if [ -f $IM_CONFIG_FILE ]; then
	IMConfigPreferredRule=$(cat $IM_CONFIG_FILE | grep "IM_CONFIG_PREFERRED_RULE=" | awk -F '=' '{print $2}')
	IMConfigPreferredRuleLine=$(cat $IM_CONFIG_FILE | grep -n "IM_CONFIG_PREFERRED_RULE=" | cut -d ":" -f 1)
    # 如果im-config配置里面没有加入dim, 则将dim加到配置规则输入法的第一位
	if [[ ! "$IMConfigPreferredRule" =~ "dim" ]]; then
        sed -i "$IMConfigPreferredRuleLine s#\,#\,dim\,#g" $IM_CONFIG_FILE
	fi
fi

#DEBHELPER#
